// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	AccountNumber        string   `protobuf:"bytes,4,opt,name=AccountNumber,proto3" json:"AccountNumber,omitempty"`
	UserEmail            string   `protobuf:"bytes,5,opt,name=UserEmail,proto3" json:"UserEmail,omitempty"`
	UserMobile           string   `protobuf:"bytes,6,opt,name=UserMobile,proto3" json:"UserMobile,omitempty"`
	UserPhone            string   `protobuf:"bytes,7,opt,name=UserPhone,proto3" json:"UserPhone,omitempty"`
	Username             string   `protobuf:"bytes,8,opt,name=Username,proto3" json:"Username,omitempty"`
	RoleID               string   `protobuf:"bytes,9,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Password             string   `protobuf:"bytes,10,opt,name=Password,proto3" json:"Password,omitempty"`
	AdminApproval        string   `protobuf:"bytes,11,opt,name=AdminApproval,proto3" json:"AdminApproval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *User) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *User) GetUserMobile() string {
	if m != nil {
		return m.UserMobile
	}
	return ""
}

func (m *User) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetRoleID() string {
	if m != nil {
		return m.RoleID
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAdminApproval() string {
	if m != nil {
		return m.AdminApproval
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{1}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{2}
}
func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (dst *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(dst, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

func (m *CreateUserReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetAllUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserRequest) Reset()         { *m = GetAllUserRequest{} }
func (m *GetAllUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllUserRequest) ProtoMessage()    {}
func (*GetAllUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{3}
}
func (m *GetAllUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserRequest.Unmarshal(m, b)
}
func (m *GetAllUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserRequest.Merge(dst, src)
}
func (m *GetAllUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllUserRequest.Size(m)
}
func (m *GetAllUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserRequest proto.InternalMessageInfo

type GetAllUserReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	User                 []*User  `protobuf:"bytes,2,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserReply) Reset()         { *m = GetAllUserReply{} }
func (m *GetAllUserReply) String() string { return proto.CompactTextString(m) }
func (*GetAllUserReply) ProtoMessage()    {}
func (*GetAllUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{4}
}
func (m *GetAllUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserReply.Unmarshal(m, b)
}
func (m *GetAllUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserReply.Marshal(b, m, deterministic)
}
func (dst *GetAllUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserReply.Merge(dst, src)
}
func (m *GetAllUserReply) XXX_Size() int {
	return xxx_messageInfo_GetAllUserReply.Size(m)
}
func (m *GetAllUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserReply proto.InternalMessageInfo

func (m *GetAllUserReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAllUserReply) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{5}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReply) Reset()         { *m = UpdateUserReply{} }
func (m *UpdateUserReply) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReply) ProtoMessage()    {}
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{6}
}
func (m *UpdateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReply.Unmarshal(m, b)
}
func (m *UpdateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReply.Marshal(b, m, deterministic)
}
func (dst *UpdateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReply.Merge(dst, src)
}
func (m *UpdateUserReply) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReply.Size(m)
}
func (m *UpdateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReply proto.InternalMessageInfo

func (m *UpdateUserReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateUserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{7}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeleteUserReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReply) Reset()         { *m = DeleteUserReply{} }
func (m *DeleteUserReply) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReply) ProtoMessage()    {}
func (*DeleteUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{8}
}
func (m *DeleteUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReply.Unmarshal(m, b)
}
func (m *DeleteUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReply.Marshal(b, m, deterministic)
}
func (dst *DeleteUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReply.Merge(dst, src)
}
func (m *DeleteUserReply) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReply.Size(m)
}
func (m *DeleteUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReply proto.InternalMessageInfo

func (m *DeleteUserReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteUserReply) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetUserRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{9}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetUserReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReply) Reset()         { *m = GetUserReply{} }
func (m *GetUserReply) String() string { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()    {}
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_08313b22856ebc68, []int{10}
}
func (m *GetUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReply.Unmarshal(m, b)
}
func (m *GetUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReply.Marshal(b, m, deterministic)
}
func (dst *GetUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReply.Merge(dst, src)
}
func (m *GetUserReply) XXX_Size() int {
	return xxx_messageInfo_GetUserReply.Size(m)
}
func (m *GetUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReply proto.InternalMessageInfo

func (m *GetUserReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "pb.CreateUserReply")
	proto.RegisterType((*GetAllUserRequest)(nil), "pb.GetAllUserRequest")
	proto.RegisterType((*GetAllUserReply)(nil), "pb.GetAllUserReply")
	proto.RegisterType((*UpdateUserRequest)(nil), "pb.UpdateUserRequest")
	proto.RegisterType((*UpdateUserReply)(nil), "pb.UpdateUserReply")
	proto.RegisterType((*DeleteUserRequest)(nil), "pb.DeleteUserRequest")
	proto.RegisterType((*DeleteUserReply)(nil), "pb.DeleteUserReply")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetUserReply)(nil), "pb.GetUserReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...grpc.CallOption) (*GetAllUserReply, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserReply, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserReply, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, "/pb.Users/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...grpc.CallOption) (*GetAllUserReply, error) {
	out := new(GetAllUserReply)
	err := c.cc.Invoke(ctx, "/pb.Users/GetAllUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserReply, error) {
	out := new(UpdateUserReply)
	err := c.cc.Invoke(ctx, "/pb.Users/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserReply, error) {
	out := new(DeleteUserReply)
	err := c.cc.Invoke(ctx, "/pb.Users/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := c.cc.Invoke(ctx, "/pb.Users/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	GetAllUser(context.Context, *GetAllUserRequest) (*GetAllUserReply, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserReply, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserReply, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetAllUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetAllUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/GetAllUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetAllUser(ctx, req.(*GetAllUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Users_CreateUser_Handler,
		},
		{
			MethodName: "GetAllUser",
			Handler:    _Users_GetAllUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Users_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Users_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Users_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_users_08313b22856ebc68) }

var fileDescriptor_users_08313b22856ebc68 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x6a, 0xdc, 0x30,
	0x14, 0x25, 0xca, 0x64, 0x1e, 0x77, 0xda, 0xa4, 0xa3, 0xd0, 0x22, 0x42, 0x28, 0xc1, 0xed, 0xa2,
	0xab, 0x29, 0x49, 0x37, 0x86, 0xae, 0x86, 0xba, 0x09, 0x86, 0x26, 0x84, 0x81, 0x7c, 0x80, 0x9d,
	0xb9, 0xb4, 0x06, 0xd9, 0x52, 0x25, 0xbb, 0x25, 0x7f, 0xd3, 0xcf, 0xe9, 0x67, 0x15, 0x49, 0x7e,
	0x68, 0xec, 0x10, 0x1a, 0x66, 0x79, 0xce, 0xd5, 0x39, 0xf7, 0x71, 0x8c, 0x61, 0x5e, 0x69, 0x54,
	0x7a, 0x29, 0x95, 0x28, 0x05, 0x25, 0x32, 0x0d, 0xfe, 0x12, 0x18, 0xdd, 0x69, 0x54, 0xf4, 0x10,
	0x48, 0x1c, 0xb1, 0xbd, 0xb3, 0xbd, 0x0f, 0xb3, 0x35, 0x89, 0x23, 0x7a, 0x0a, 0xb3, 0xcb, 0x4c,
	0xe9, 0xf2, 0x26, 0xc9, 0x91, 0x11, 0x4b, 0x77, 0x04, 0x3d, 0x81, 0xe9, 0xb7, 0xa4, 0x2e, 0xee,
	0xdb, 0x62, 0x8b, 0xe9, 0x7b, 0x78, 0xb9, 0xba, 0xbf, 0x17, 0x55, 0x51, 0xde, 0x54, 0x79, 0x8a,
	0x8a, 0x8d, 0xec, 0x83, 0x6d, 0xd2, 0xf8, 0x9b, 0xbe, 0x5f, 0xf3, 0x24, 0xe3, 0xec, 0xc0, 0xf9,
	0xb7, 0x04, 0x7d, 0x0b, 0x60, 0xc0, 0xb5, 0x48, 0x33, 0x8e, 0x6c, 0x6c, 0xcb, 0x1e, 0xd3, 0xa8,
	0x6f, 0x7f, 0x88, 0x02, 0xd9, 0xa4, 0x53, 0x5b, 0xc2, 0x4c, 0x67, 0x40, 0x61, 0xa6, 0x9b, 0xba,
	0xe9, 0x1a, 0x4c, 0xdf, 0xc0, 0x78, 0x2d, 0x38, 0xc6, 0x11, 0x9b, 0xd9, 0x4a, 0x8d, 0x8c, 0xe6,
	0x36, 0xd1, 0xfa, 0xb7, 0x50, 0x1b, 0x06, 0x4e, 0xd3, 0x60, 0xbb, 0xd1, 0x26, 0xcf, 0x8a, 0x95,
	0x94, 0x4a, 0xfc, 0x4a, 0x38, 0x9b, 0xd7, 0x1b, 0xf9, 0x64, 0x70, 0x0e, 0x8b, 0x2f, 0x0a, 0x93,
	0x12, 0x4d, 0xaf, 0x35, 0xfe, 0xac, 0x50, 0x97, 0xf4, 0x14, 0x46, 0xe6, 0xe4, 0xf6, 0xb0, 0xf3,
	0x8b, 0xe9, 0x52, 0xa6, 0x4b, 0x5b, 0xb6, 0x6c, 0x10, 0xc3, 0x91, 0x2f, 0x91, 0xfc, 0x81, 0x32,
	0x98, 0x5c, 0xa3, 0xd6, 0xc9, 0x77, 0xac, 0xc3, 0x68, 0x60, 0x6b, 0x45, 0x1e, 0xb5, 0x3a, 0x86,
	0xc5, 0x15, 0x96, 0x2b, 0xce, 0xbd, 0xee, 0xc6, 0xdf, 0x27, 0xff, 0xd7, 0x7f, 0xff, 0x11, 0xff,
	0x73, 0x58, 0xdc, 0xc9, 0xcd, 0x73, 0xb7, 0xf3, 0x25, 0xbb, 0x6c, 0xf7, 0x0e, 0x16, 0x11, 0x72,
	0xdc, 0xee, 0xde, 0xfb, 0x64, 0x83, 0xcf, 0x70, 0xe4, 0x3f, 0x7a, 0xba, 0x9f, 0x13, 0x93, 0x56,
	0x7c, 0x06, 0x87, 0x57, 0x58, 0x3e, 0x65, 0x7f, 0x09, 0x2f, 0xda, 0x17, 0x3b, 0xec, 0x72, 0xf1,
	0x87, 0xc0, 0x81, 0x81, 0x9a, 0x86, 0x00, 0x5d, 0xfc, 0xf4, 0xb5, 0x79, 0x37, 0xf8, 0x82, 0x4e,
	0x8e, 0xfb, 0xb4, 0xe9, 0x1d, 0x02, 0x74, 0xc1, 0x3a, 0xe5, 0x20, 0x7d, 0xa7, 0xec, 0xe7, 0x1f,
	0x02, 0x74, 0xa1, 0x38, 0xe5, 0x20, 0x57, 0xa7, 0xec, 0x67, 0x17, 0x02, 0x74, 0xe7, 0x75, 0xca,
	0x41, 0x26, 0x4e, 0xd9, 0x4f, 0xe1, 0x23, 0x4c, 0xea, 0xcb, 0x51, 0x5a, 0xcf, 0xe4, 0x6b, 0x5e,
	0x6d, 0x71, 0x92, 0x3f, 0xa4, 0x63, 0xfb, 0x83, 0xfa, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x3c,
	0x1e, 0x3f, 0xc5, 0xaf, 0x04, 0x00, 0x00,
}
