// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{0}
}
func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (dst *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(dst, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

type CreateProductReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductReply) Reset()         { *m = CreateProductReply{} }
func (m *CreateProductReply) String() string { return proto.CompactTextString(m) }
func (*CreateProductReply) ProtoMessage()    {}
func (*CreateProductReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{1}
}
func (m *CreateProductReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductReply.Unmarshal(m, b)
}
func (m *CreateProductReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductReply.Marshal(b, m, deterministic)
}
func (dst *CreateProductReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductReply.Merge(dst, src)
}
func (m *CreateProductReply) XXX_Size() int {
	return xxx_messageInfo_CreateProductReply.Size(m)
}
func (m *CreateProductReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductReply proto.InternalMessageInfo

type GetAllProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductRequest) Reset()         { *m = GetAllProductRequest{} }
func (m *GetAllProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProductRequest) ProtoMessage()    {}
func (*GetAllProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{2}
}
func (m *GetAllProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductRequest.Unmarshal(m, b)
}
func (m *GetAllProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductRequest.Merge(dst, src)
}
func (m *GetAllProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProductRequest.Size(m)
}
func (m *GetAllProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductRequest proto.InternalMessageInfo

type GetAllProductReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductReply) Reset()         { *m = GetAllProductReply{} }
func (m *GetAllProductReply) String() string { return proto.CompactTextString(m) }
func (*GetAllProductReply) ProtoMessage()    {}
func (*GetAllProductReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{3}
}
func (m *GetAllProductReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductReply.Unmarshal(m, b)
}
func (m *GetAllProductReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductReply.Marshal(b, m, deterministic)
}
func (dst *GetAllProductReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductReply.Merge(dst, src)
}
func (m *GetAllProductReply) XXX_Size() int {
	return xxx_messageInfo_GetAllProductReply.Size(m)
}
func (m *GetAllProductReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductReply proto.InternalMessageInfo

type UpdateProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{4}
}
func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(dst, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

type UpdateProductReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductReply) Reset()         { *m = UpdateProductReply{} }
func (m *UpdateProductReply) String() string { return proto.CompactTextString(m) }
func (*UpdateProductReply) ProtoMessage()    {}
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{5}
}
func (m *UpdateProductReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductReply.Unmarshal(m, b)
}
func (m *UpdateProductReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductReply.Marshal(b, m, deterministic)
}
func (dst *UpdateProductReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductReply.Merge(dst, src)
}
func (m *UpdateProductReply) XXX_Size() int {
	return xxx_messageInfo_UpdateProductReply.Size(m)
}
func (m *UpdateProductReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductReply proto.InternalMessageInfo

type DeleteProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{6}
}
func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(dst, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

type DeleteProductReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductReply) Reset()         { *m = DeleteProductReply{} }
func (m *DeleteProductReply) String() string { return proto.CompactTextString(m) }
func (*DeleteProductReply) ProtoMessage()    {}
func (*DeleteProductReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{7}
}
func (m *DeleteProductReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductReply.Unmarshal(m, b)
}
func (m *DeleteProductReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductReply.Marshal(b, m, deterministic)
}
func (dst *DeleteProductReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductReply.Merge(dst, src)
}
func (m *DeleteProductReply) XXX_Size() int {
	return xxx_messageInfo_DeleteProductReply.Size(m)
}
func (m *DeleteProductReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductReply proto.InternalMessageInfo

type GetProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{8}
}
func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(dst, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

type GetProductReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductReply) Reset()         { *m = GetProductReply{} }
func (m *GetProductReply) String() string { return proto.CompactTextString(m) }
func (*GetProductReply) ProtoMessage()    {}
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{9}
}
func (m *GetProductReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductReply.Unmarshal(m, b)
}
func (m *GetProductReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductReply.Marshal(b, m, deterministic)
}
func (dst *GetProductReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductReply.Merge(dst, src)
}
func (m *GetProductReply) XXX_Size() int {
	return xxx_messageInfo_GetProductReply.Size(m)
}
func (m *GetProductReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductReply proto.InternalMessageInfo

type UpdateProductStockRequest struct {
	AddStock             bool            `protobuf:"varint,1,opt,name=AddStock,proto3" json:"AddStock,omitempty"`
	RemoveStock          bool            `protobuf:"varint,2,opt,name=RemoveStock,proto3" json:"RemoveStock,omitempty"`
	ProductStock         []*ProductStock `protobuf:"bytes,3,rep,name=ProductStock,proto3" json:"ProductStock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateProductStockRequest) Reset()         { *m = UpdateProductStockRequest{} }
func (m *UpdateProductStockRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductStockRequest) ProtoMessage()    {}
func (*UpdateProductStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{10}
}
func (m *UpdateProductStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductStockRequest.Unmarshal(m, b)
}
func (m *UpdateProductStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductStockRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateProductStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductStockRequest.Merge(dst, src)
}
func (m *UpdateProductStockRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductStockRequest.Size(m)
}
func (m *UpdateProductStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductStockRequest proto.InternalMessageInfo

func (m *UpdateProductStockRequest) GetAddStock() bool {
	if m != nil {
		return m.AddStock
	}
	return false
}

func (m *UpdateProductStockRequest) GetRemoveStock() bool {
	if m != nil {
		return m.RemoveStock
	}
	return false
}

func (m *UpdateProductStockRequest) GetProductStock() []*ProductStock {
	if m != nil {
		return m.ProductStock
	}
	return nil
}

type UpdateProductStockReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductStockReply) Reset()         { *m = UpdateProductStockReply{} }
func (m *UpdateProductStockReply) String() string { return proto.CompactTextString(m) }
func (*UpdateProductStockReply) ProtoMessage()    {}
func (*UpdateProductStockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{11}
}
func (m *UpdateProductStockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductStockReply.Unmarshal(m, b)
}
func (m *UpdateProductStockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductStockReply.Marshal(b, m, deterministic)
}
func (dst *UpdateProductStockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductStockReply.Merge(dst, src)
}
func (m *UpdateProductStockReply) XXX_Size() int {
	return xxx_messageInfo_UpdateProductStockReply.Size(m)
}
func (m *UpdateProductStockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductStockReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductStockReply proto.InternalMessageInfo

func (m *UpdateProductStockReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProductStock struct {
	ProductID            uint64   `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	ProductsQuantity     uint64   `protobuf:"varint,2,opt,name=ProductsQuantity,proto3" json:"ProductsQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductStock) Reset()         { *m = ProductStock{} }
func (m *ProductStock) String() string { return proto.CompactTextString(m) }
func (*ProductStock) ProtoMessage()    {}
func (*ProductStock) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_baba5062d922652b, []int{12}
}
func (m *ProductStock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductStock.Unmarshal(m, b)
}
func (m *ProductStock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductStock.Marshal(b, m, deterministic)
}
func (dst *ProductStock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductStock.Merge(dst, src)
}
func (m *ProductStock) XXX_Size() int {
	return xxx_messageInfo_ProductStock.Size(m)
}
func (m *ProductStock) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductStock.DiscardUnknown(m)
}

var xxx_messageInfo_ProductStock proto.InternalMessageInfo

func (m *ProductStock) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *ProductStock) GetProductsQuantity() uint64 {
	if m != nil {
		return m.ProductsQuantity
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateProductRequest)(nil), "pb.CreateProductRequest")
	proto.RegisterType((*CreateProductReply)(nil), "pb.CreateProductReply")
	proto.RegisterType((*GetAllProductRequest)(nil), "pb.GetAllProductRequest")
	proto.RegisterType((*GetAllProductReply)(nil), "pb.GetAllProductReply")
	proto.RegisterType((*UpdateProductRequest)(nil), "pb.UpdateProductRequest")
	proto.RegisterType((*UpdateProductReply)(nil), "pb.UpdateProductReply")
	proto.RegisterType((*DeleteProductRequest)(nil), "pb.DeleteProductRequest")
	proto.RegisterType((*DeleteProductReply)(nil), "pb.DeleteProductReply")
	proto.RegisterType((*GetProductRequest)(nil), "pb.GetProductRequest")
	proto.RegisterType((*GetProductReply)(nil), "pb.GetProductReply")
	proto.RegisterType((*UpdateProductStockRequest)(nil), "pb.UpdateProductStockRequest")
	proto.RegisterType((*UpdateProductStockReply)(nil), "pb.UpdateProductStockReply")
	proto.RegisterType((*ProductStock)(nil), "pb.ProductStock")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductReply, error)
	GetAllProduct(ctx context.Context, in *GetAllProductRequest, opts ...grpc.CallOption) (*GetAllProductReply, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductReply, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductReply, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error)
	UpdateProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockReply, error)
}

type productsClient struct {
	cc *grpc.ClientConn
}

func NewProductsClient(cc *grpc.ClientConn) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductReply, error) {
	out := new(CreateProductReply)
	err := c.cc.Invoke(ctx, "/pb.Products/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetAllProduct(ctx context.Context, in *GetAllProductRequest, opts ...grpc.CallOption) (*GetAllProductReply, error) {
	out := new(GetAllProductReply)
	err := c.cc.Invoke(ctx, "/pb.Products/GetAllProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductReply, error) {
	out := new(UpdateProductReply)
	err := c.cc.Invoke(ctx, "/pb.Products/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductReply, error) {
	out := new(DeleteProductReply)
	err := c.cc.Invoke(ctx, "/pb.Products/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error) {
	out := new(GetProductReply)
	err := c.cc.Invoke(ctx, "/pb.Products/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) UpdateProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockReply, error) {
	out := new(UpdateProductStockReply)
	err := c.cc.Invoke(ctx, "/pb.Products/UpdateProductStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
type ProductsServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductReply, error)
	GetAllProduct(context.Context, *GetAllProductRequest) (*GetAllProductReply, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductReply, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductReply, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error)
	UpdateProductStock(context.Context, *UpdateProductStockRequest) (*UpdateProductStockReply, error)
}

func RegisterProductsServer(s *grpc.Server, srv ProductsServer) {
	s.RegisterService(&_Products_serviceDesc, srv)
}

func _Products_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Products/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetAllProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetAllProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Products/GetAllProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetAllProduct(ctx, req.(*GetAllProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Products/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Products/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Products/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_UpdateProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).UpdateProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Products/UpdateProductStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).UpdateProductStock(ctx, req.(*UpdateProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Products_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _Products_CreateProduct_Handler,
		},
		{
			MethodName: "GetAllProduct",
			Handler:    _Products_GetAllProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _Products_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _Products_DeleteProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _Products_GetProduct_Handler,
		},
		{
			MethodName: "UpdateProductStock",
			Handler:    _Products_UpdateProductStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products.proto",
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_products_baba5062d922652b) }

var fileDescriptor_products_baba5062d922652b = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4d, 0x4f, 0xfa, 0x40,
	0x10, 0xc6, 0xc3, 0x4b, 0xfe, 0x7f, 0x18, 0x44, 0x61, 0x40, 0xac, 0xa8, 0x09, 0xe9, 0x89, 0x78,
	0xe0, 0x00, 0x1e, 0xbc, 0x36, 0x92, 0x10, 0x6f, 0x58, 0x63, 0xe2, 0x15, 0xe8, 0xc4, 0x18, 0x8b,
	0x5d, 0xe9, 0xd6, 0xa4, 0x9f, 0xc2, 0xef, 0xe0, 0x27, 0x35, 0xdb, 0x5d, 0xa4, 0xfb, 0xe2, 0x71,
	0x9e, 0x79, 0xf6, 0x99, 0xd9, 0xee, 0xaf, 0x70, 0xcc, 0x76, 0x49, 0x94, 0x6d, 0x78, 0x3a, 0x61,
	0xbb, 0x84, 0x27, 0x58, 0x65, 0x6b, 0x7f, 0x00, 0xfd, 0xbb, 0x1d, 0xad, 0x38, 0x2d, 0x65, 0x2f,
	0xa4, 0x8f, 0x8c, 0x52, 0xee, 0xf7, 0x01, 0x0d, 0x9d, 0xc5, 0xb9, 0x70, 0x2f, 0x88, 0x07, 0x71,
	0x6c, 0xbb, 0x0d, 0x5d, 0xb9, 0x9f, 0x58, 0xe4, 0xcc, 0x36, 0x74, 0xe5, 0x9e, 0x53, 0x4c, 0x2e,
	0xb7, 0xa1, 0x0b, 0x77, 0x0f, 0xba, 0x0b, 0xe2, 0x86, 0xb5, 0x0b, 0x27, 0x65, 0x51, 0xf8, 0xbe,
	0x2a, 0x70, 0xae, 0x0d, 0x7b, 0xe4, 0xc9, 0xe6, 0x4d, 0x1d, 0xc0, 0x21, 0x34, 0x82, 0x28, 0x2a,
	0x24, 0xaf, 0x32, 0xaa, 0x8c, 0x1b, 0xe1, 0x6f, 0x8d, 0x23, 0x68, 0x85, 0xb4, 0x4d, 0x3e, 0x49,
	0xb6, 0xab, 0x45, 0xbb, 0x2c, 0xe1, 0x0d, 0x1c, 0x95, 0x43, 0xbd, 0xda, 0xa8, 0x36, 0x6e, 0x4d,
	0x3b, 0x13, 0xb6, 0x9e, 0x68, 0xc3, 0x34, 0x97, 0x3f, 0x83, 0x33, 0xd7, 0x42, 0x2c, 0xce, 0xd1,
	0x83, 0xff, 0x5b, 0x4a, 0xd3, 0xd5, 0x0b, 0x15, 0xdb, 0x34, 0xc3, 0x7d, 0xe9, 0x3f, 0xeb, 0xa3,
	0xf0, 0x12, 0x9a, 0xaa, 0xbe, 0x9f, 0x17, 0xde, 0x7a, 0x78, 0x10, 0xf0, 0x1a, 0x3a, 0xaa, 0x48,
	0x1f, 0xb2, 0xd5, 0x3b, 0x7f, 0xe5, 0x79, 0xb1, 0x7f, 0x3d, 0xb4, 0xf4, 0xe9, 0x77, 0x0d, 0x1a,
	0x7b, 0x11, 0x03, 0x68, 0x6b, 0xaf, 0x8e, 0x9e, 0xb8, 0x8c, 0x0b, 0x90, 0xe1, 0xc0, 0xd1, 0x11,
	0x77, 0x08, 0xa0, 0xad, 0xa1, 0x20, 0x23, 0x5c, 0xd4, 0xc8, 0x08, 0x9b, 0x1b, 0x11, 0xa1, 0x7d,
	0x21, 0x19, 0xe1, 0x42, 0x49, 0x46, 0xd8, 0x30, 0x89, 0x08, 0x0d, 0x1a, 0x19, 0xe1, 0xe2, 0x4b,
	0x46, 0xd8, 0x84, 0xe1, 0x2d, 0xc0, 0x01, 0x26, 0x3c, 0x55, 0xbb, 0x1a, 0x87, 0x7b, 0xa6, 0x2c,
	0x4e, 0x2e, 0x0d, 0xbe, 0xe5, 0x93, 0x5d, 0x59, 0xab, 0x96, 0x51, 0x1c, 0x5e, 0xfc, 0xd5, 0x66,
	0x71, 0xbe, 0xfe, 0x57, 0xfc, 0xb0, 0xb3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x30, 0x2a,
	0xdb, 0xc2, 0x03, 0x00, 0x00,
}
