// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "gokit/ecommerse/carts/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeAddToCartHandler(m, endpoints, options["AddToCart"])
	makeGetFromAllHandler(m, endpoints, options["GetFromAll"])
	makeUpdateInCartHandler(m, endpoints, options["UpdateInCart"])
	makeDeleteFromCartHandler(m, endpoints, options["DeleteFromCart"])
	makeGetFromCartHandler(m, endpoints, options["GetFromCart"])
	return m
}
