version: "2"
services:


  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql

  db:
    image: mysql:5.7
    container_name: db
    environment:
      # MYSQL_USER: rahul
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - ecommerce-db:/var/lib/mysql
    ports:
      - 9096:3306

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    depends_on:
      - storage

  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      # Add the baked-in username and password for the zipkin-mysql image
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      # Uncomment to see dependency processing logs
      # - ZIPKIN_LOG_LEVEL=DEBUG
      # Uncomment to adjust memory used by the dependencies job
      # - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
    depends_on:
      - storage

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9191:80
    external_links:
    - db:mysql
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_PASSWORD: password
      # MYSQL_USER: rahul
      
    # expose:
    #   ["3308"]

    # adminer:
    # image: adminer
    # restart: always
    # ports:
    #   - 8080:8080

  carts:
    depends_on:
      - db
    build:
      context: .
      dockerfile: carts/Dockerfile
    restart: always
    volumes:
    - .:/go/src/gokit/ecommerse
    container_name: carts
    ports:
    - 8803:8081
  products:
    depends_on:
      - db
    build:
      context: .
      dockerfile: products/Dockerfile
    container_name: products
    ports:
    - 8802:8081
    restart: always
    volumes:
    - .:/go/src/gokit/ecommerse
  users:
    depends_on:
      - db
      - zipkin
    build:
      context: .
      dockerfile: users/Dockerfile
    container_name: users
    ports:
    - 8800:8081
    - 8801:8082
    restart: always
    volumes:
    - .:/go/src/gokit/ecommerse
volumes:  
  ecommerce-db:
