// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "gokit/ecommerse/users/pkg/endpoint"
	pb "gokit/ecommerse/users/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createUser grpc.Handler
	getAllUser grpc.Handler
	updateUser grpc.Handler
	deleteUser grpc.Handler
	getUser    grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.UsersServer {
	return &grpcServer{
		createUser: makeCreateUserHandler(endpoints, options["CreateUser"]),
		deleteUser: makeDeleteUserHandler(endpoints, options["DeleteUser"]),
		getAllUser: makeGetAllUserHandler(endpoints, options["GetAllUser"]),
		getUser:    makeGetUserHandler(endpoints, options["GetUser"]),
		updateUser: makeUpdateUserHandler(endpoints, options["UpdateUser"]),
	}
}
