// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "gokit/ecommerse/users/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeCreateUserHandler(m, endpoints, options["CreateUser"])
	makeGetAllUserHandler(m, endpoints, options["GetAllUser"])
	makeUpdateUserHandler(m, endpoints, options["UpdateUser"])
	makeDeleteUserHandler(m, endpoints, options["DeleteUser"])
	makeGetUserHandler(m, endpoints, options["GetUser"])
	return m
}
