// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "gokit/ecommerse/products/pkg/endpoint"
	pb "gokit/ecommerse/products/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createProduct      grpc.Handler
	getAllProduct      grpc.Handler
	updateProduct      grpc.Handler
	deleteProduct      grpc.Handler
	getProduct         grpc.Handler
	updateProductStock grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.ProductsServer {
	return &grpcServer{
		createProduct:      makeCreateProductHandler(endpoints, options["CreateProduct"]),
		deleteProduct:      makeDeleteProductHandler(endpoints, options["DeleteProduct"]),
		getAllProduct:      makeGetAllProductHandler(endpoints, options["GetAllProduct"]),
		getProduct:         makeGetProductHandler(endpoints, options["GetProduct"]),
		updateProduct:      makeUpdateProductHandler(endpoints, options["UpdateProduct"]),
		updateProductStock: makeUpdateProductStockHandler(endpoints, options["UpdateProductStock"]),
	}
}
