// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "gokit/ecommerse/orders/pkg/endpoint"
	pb "gokit/ecommerse/orders/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createOrder grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.OrdersServer {
	return &grpcServer{createOrder: makeCreateOrderHandler(endpoints, options["CreateOrder"])}
}
