// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
	endpoint "gokit/ecommerse/products/pkg/endpoint"
	http1 "gokit/ecommerse/products/pkg/http"
	service "gokit/ecommerse/products/pkg/service"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"CreateProduct": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateProduct", logger))},
		"DeleteProduct": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DeleteProduct", logger))},
		"GetAllProduct": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetAllProduct", logger))},
		"GetProduct":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetProduct", logger))},
		"UpdateProduct": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UpdateProduct", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["CreateProduct"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateProduct")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateProduct"))}
	mw["GetAllProduct"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetAllProduct")), endpoint.InstrumentingMiddleware(duration.With("method", "GetAllProduct"))}
	mw["UpdateProduct"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UpdateProduct")), endpoint.InstrumentingMiddleware(duration.With("method", "UpdateProduct"))}
	mw["DeleteProduct"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DeleteProduct")), endpoint.InstrumentingMiddleware(duration.With("method", "DeleteProduct"))}
	mw["GetProduct"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetProduct")), endpoint.InstrumentingMiddleware(duration.With("method", "GetProduct"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"CreateProduct", "GetAllProduct", "UpdateProduct", "DeleteProduct", "GetProduct"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
